var header_grammar = {
  "origin": "#sentence#",
  "sentence" : [
    "#buzzverb#ing your #buzznoun#s so you don't have to."
  ],
  "suffix": [
    "",
    "ing",
    "ed"
  ],
  "buzzdverb": [
    "dynamically",
    "ethically",
    "reliably",
    "deeply"
  ],
  "buzzjective": [
    "seamless",
    "unparalleled",
    "immersive",
    "proactive",
    "mission critical",
    "innovative",
    "scalable",
    "personalized",
    "integrated",
    "cross-platform",
    "targeted",
    "segmented",
    "optimal",
    "sustainable",
    "streamline",
    "omnichannel",
    "bleeding edge",
    "predictive",
    "modular",
    "end-to-end",
    "enterprise-level",
    "real-time",
    "on-demand",
    "restful",
    "distributed",
    "functional",
    "best-in-class",
    "legacy",
    "non-linear",
    "concurrent"
  ],
  "buzzverb": [
    "engineer",
    "enable",
    "engage",
    "execute",
    "enhance",
    "datafy"
  ],
  "buzznoun": [
    "crypto-currency",
    "machine-learning",
    "bloatware",
    "KPI",
    "transparency",
    "microservice",
    "Web 2.0",
    "web assembly",
    "data science",
    "analytics",
    "return on investment",
    "industry leader",
    "best practice",
    "agile workflow",
    "user experience",
    "organic growth",
    "big data",
    "team player",
    "emerging market",
    "scalability",
    "core asset",
    "front-end developer",
    "API",
    "framework",
    "cloud computing",
    "millenial",
    "responsive web design",
    "architecture",
    "information superhighway",
    "world wide web",
    "hyperlink",
    "development lifecycle"
  ]
}