var buzzword_grammar = {
  "origin": "#sentence#",
  "sentence" : [
    "Our #buzzjective# #buzznoun# #buzzverb#s #buzzjective#, #buzzjective# #buzznoun-plural#.",
    "It's critical that we use #buzzjective# #buzznoun#s in order to #buzzverb# the types of #buzznoun-plural# our customers #buzzverb#.",
    "We aim to #buzzverb# our #buzznoun# by #buzzdverb# #buzzverb#ing our #buzznoun-plural#.",
      "Engagement of our #buzznoun# results in #buzzverb#ing our client's #buzznoun-plural#."
  ],
  "suffix": [
    "",
    "ing",
    "ed"
  ],
  "buzzdverb": [
    "dynamically",
    "ethically",
    "reliably",
    "deeply"
  ],
  "buzzjective": [
    "seamless",
    "unparalleled",
    "immersive",
    "proactive",
    "mission critical",
    "innovative",
    "scalable",
    "personalized",
    "integrated",
    "cross-platform",
    "targeted",
    "segmented",
    "optimal",
    "sustainable",
    "streamline",
    "omnichannel",
    "bleeding edge",
    "predictive",
    "modular",
    "end-to-end",
    "enterprise-level",
    "real-time",
    "on-demand",
    "restful",
    "distributed",
    "functional",
    "best-in-class",
    "legacy",
    "non-linear",
    "concurrent"
  ],
  "buzzverb": [
    "engineer",
    "reuse",
    "adopt",
    "enable",
    "engage",
    "drive",
    "execute",
    "enhance",
    "spin-up",
    "touch-base",
    "datafy",
    "expect"
  ],
  "buzznoun": [
    "crypto-currency",
    "machine-learning",
    "bloatware",
    "KPI",
    "transparency",
    "microservice",
    "Web 2.0",
    "web assembly",
    "data science",
    "analytics",
    "return on investment",
    "industry leader",
    "best practice",
    "agile workflow",
    "user experience",
    "organic growth",
    "big data",
    "team player",
    "emerging market",
    "scalability",
    "core asset",
    "front-end developer",
    "API",
    "framework",
    "cloud computing",
    "millenial",
    "responsive web design",
    "architecture",
    "information super-highway",
    "world wide web",
    "hyperlink",
    "development lifecycle"
  ],
    "buzznoun-plural": [
        "crypto-currencies",
        "machine-learnings",
        "bloatwares",
        "KPIs",
        "transparencies",
        "microservices",
        "Web 2.0s",
        "web assemblies",
        "data sciences",
        "analytics",
        "return on investments",
        "industry leaders",
        "best practices",
        "agile workflows",
        "user experiences",
        "organic growths",
        "big datas",
        "team players",
        "emerging markets",
        "scalabilities",
        "core assets",
        "front-end developers",
        "APIs",
        "frameworks",
        "cloud computings",
        "millenials",
        "responsive web designs",
        "architectures",
        "information super-highways",
        "world wide webs",
        "hyperlinks",
        "development lifecycles"
    ]

};